[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 8192
multiplier = 3

[window]
decorations = "none"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 3
y = 0

# ---- Dark Theme

[colors.bright]
black = "0x2d3437"
blue = "0x71baf2"
cyan = "0x67cbe7"
green = "0x96d988"
magenta = "0xce89df"
red = "0xef7e7e"
white = "0xbdc3c2"
yellow = "0xf4d67a"

[colors.normal]
black = "0x232a2d"
blue = "0x67b0e8"
cyan = "0x6cbfbf"
green = "0x8ccf7e"
magenta = "0xc47fd5"
red = "0xe57474"
white = "0xb3b9b8"
yellow = "0xe5c76b"

[colors.primary]
background = "0x141b1e"
foreground = "0xdadada"


# ---- light theme

# [colors.primary]
# background = '#f8f8f8'
# foreground = '#2a2b33'

# [colors.normal]
# black   = '#000000'
# red     = '#de3d35'
# green   = '#3e953a'
# yellow  = '#d2b67b'
# blue    = '#2f5af3'
# magenta = '#a00095'
# cyan    = '#3e953a'
# white   = '#bbbbbb'

# [colors.bright]
# black   = '#000000'
# red     = '#de3d35'
# green   = '#3e953a'
# yellow  = '#d2b67b'
# blue    = '#2f5af3'
# magenta = '#a00095'
# cyan    = '#3e953a'
# white   = '#ffffff'


# ---- Pencil Light Theme

# [colors.primary]
# background = '#f1f1f1'
# foreground = '#424242'

# [colors.normal]
# black   = '#212121'
# red     = '#c30771'
# green   = '#10a778'
# yellow  = '#a89c14'
# blue    = '#008ec4'
# magenta = '#523c79'
# cyan    = '#20a5ba'
# white   = '#e0e0e0'

# [colors.bright]
# black   = '#212121'
# red     = '#fb007a'
# green   = '#5fd7af'
# yellow  = '#f3e430'
# blue    = '#20bbfc'
# magenta = '#6855de'
# cyan    = '#4fb8cc'
# white   = '#f1f1f1'